name: "Plugin CI/CD"

on:
  push:
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: write
    
jobs:
  plugin:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          lfs: true

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1.13.0
        with:
          arch: x86
 
      - name: Compile plugin
        run: |
          cmake . --preset G1-Release
          cmake --build --preset G1-Release

      - name: Find plugin
        run: |
          $plugin_dll = Get-ChildItem *.dll -Recurse | Select-Object -First 1 -ExpandProperty FullName
          $plugin_dll = $plugin_dll.Replace((Resolve-Path ".").Path + "\", "")
          $plugin_dll = $plugin_dll.Replace("\", "/")
          echo "plugin_dll=$plugin_dll" >> $env:GITHUB_ENV
          echo "Found plugin path: $plugin_dll"

      - name: Determine release tag
        run: |
          if ($env:GITHUB_REF_TYPE -eq "tag") {
            echo "release_tag=${env:GITHUB_REF_NAME}" >> $env:GITHUB_ENV
          } else {
            echo "release_tag=dev" >> $env:GITHUB_ENV
          }
        shell: pwsh

      - name: Upload plugin
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.release_tag }}
          body_path: changelog.md
          files: ${{ env.plugin_dll }}

      - name: Upload plugin to the Steam workshop
        run: |
          cp ${{ env.plugin_dll }} ./steam-workshop/system/autorun
          ./steam-workshop/publish.bat